cropper:
  cropR: 0
  cropR2: 0.08
  cropZ: -500
  cropZup: 330
  ladC: 0
  ladW: 0
  mesh: 2
  nfmin: 20
  nfrad: 5
  wd: 0
picker:
  azimuth:
    max: 360
    min: 0
  fitness:
    max: 10
    min: 0.8
  rotX:
    max: 20
    min: -10
  rotation:
    max: 25
    min: -25
prepro:
  box0_crop: 180
  box0_points: 100
  box0_step: 7
  box0_vcrop: 10
  box0_width: 30
  bucket_height: 330
  bucket_width: 955
  bucket_yclip: -450
  enable: 1
  peak_fitness: 0.5
  peak_length: 600
  peak_order: 20
  peak_rmse: 1.5
  peak_threshold: 3.0
  peak_width: 50
  ss_dist: -150
  ss_ry: 15
revolver:
  deg: 0
  enable: 1
rovi:
  pshift_genpc:
    calc:
      bw_diff: 8
      darkness: 5
  ycam:
    ExposureTimeLevel: 6
    camera:
      Gain: 0
    projector:
      Intensity: 250
rsocket:
  base_frame_id: ''
  source_frame_id: ''
  target_frame_id: ''
searcher:
  cutter:
    align: y
    base: -100
    crop: -5
    distance: 500
    offset: 95
    trim: 0
    width: 7
  distance_threshold: 20
  feature_mesh: 4
  feature_radius: 20
  icp_threshold: 3
  normal_min_nn: 5
  normal_radius: 8
  repeat: 1
  rotate: 0
